window.NB_TEXT={
  "ONE LAKE · SIX LOCAL GUIDES": "ÉN INNSJØ · SEKS LOKALE GUIDER",
  "Where shall we go?": "Hvor skal vi dra?",
  "Tap a place on the map. Find good food, a beer, a bed and a day by bike.": "Trykk på et sted på kartet. Finn god mat, en øl, et sted å bo og en fin sykkeltur.",
  "◎ Biking around the lake →": "◎ På sykkel rundt innsjøen →",
  "Find a bike": "Finn en sykkel",
  "Bike sharing, rentals and where to return them": "Bysykkel, utleie og hvor sykkelen kan leveres",
  "Get to know Bodensee": "Bli kjent med Bodensee",
  "Geography, history and how the shores fit together": "Geografi, historie og hvordan områdene henger sammen",
  "The pub & beer guide": "Pub- og ølguiden",
  "Pubs, brewery bars and beer gardens around the lake": "Puber, bryggeribarer og ølhager rundt innsjøen",
  "Six guides": "Seks guider",
  "Bike hire": "Sykkelleie",
  "Pubs & bars": "Puber og barer",
  "Hotels": "Hoteller",
  "Sights & visits": "Se og opplev",
  "Breweries": "Bryggerier",
  "Enlarge map": "Forstørr kartet",
  "Detailed Lake Constance shoreline from OpenStreetMap, with six clickable guides": "Detaljert strandlinje for Bodensee fra OpenStreetMap, med seks guider du kan åpne",
  "GERMANY": "TYSKLAND",
  "SWITZERLAND": "SVEITS",
  "AUSTRIA": "ØSTERRIKE",
  "Ueberlinger See": "Überlinger See",
  "Swiss shore": "Sveitsisk bredd",
  "Dashed lines: main car-ferry crossings": "Stiplede linjer: de viktigste bilfergene",
  "Detailed shoreline; landscape shading is illustrative.": "Detaljert strandlinje. Terrengfargene er illustrative.",
  "Zoom in for detail. Swipe to move around the map.": "Zoom inn for detaljer. Sveip for å flytte kartet.",
  "Old lanes, a harbour beer, island detours": "Gamle smug, en øl ved havnen og øyutflukter",
  "Castle walls and long lake views": "Slottsmurer og vid utsikt over innsjøen",
  "Airships, country breweries, a Swiss ferry": "Luftskip, bygdebryggerier og ferge til Sveits",
  "The strongest little evening cluster": "Mange hyggelige kveldssteder på et lite område",
  "A swim, a mountain view, a lakeside table": "Et bad, fjellutsikt og et bord ved vannet",
  "The Swiss shore": "Den sveitsiske bredden",
  "Harbour pauses and Swiss brewery bars": "Havnepauser og sveitsiske bryggeribarer",
  "Detailed shoreline overview ·": "Detaljert oversiktskart ·",
  "© OpenStreetMap contributors": "© OpenStreetMap-bidragsytere",
  "· Not riding directions.": "· Ikke rutebeskrivelse for sykling.",
  "← The six places": "← De seks stedene",
  "THE LAKE AT YOUR OWN PACE": "INNSJØEN I DITT EGET TEMPO",
  "A good day by bike.": "En god dag på sykkel.",
  "Choose a base, make a small outing, and come back for dinner. You do not need to circle the whole lake to enjoy it.": "Velg en base, ta en liten utflukt og kom tilbake til middag. Du trenger ikke sykle rundt hele innsjøen for å nyte den.",
  "Start with one shore": "Start med én bredd",
  "Each of the six guides includes an outing from that area. Begin with a short out-and-back: you can turn around whenever you like. Leave time for a swim, a museum or a long lunch. The inland hop country and upper towns add climbing; an e-bike helps, but does not make every route effortless.": "Hver av de seks guidene har et turforslag fra området. Begynn med en kort tur frem og tilbake, så kan du snu når du vil. Sett av tid til et bad, et museum eller en lang lunsj. Humleområdet innover i landet og de høyereliggende bydelene byr på bakker. En elsykkel hjelper, men gjør ikke alle ruter lette.",
  "Build your ride in three steps": "Planlegg turen i tre trinn",
  "Choose a destination you actually want to visit, then check a cycling route from your accommodation.": "Velg et sted du faktisk vil besøke, og finn deretter en sykkelrute fra overnattingsstedet.",
  "Check the return distance, terrain, weather and battery range. Keep a comfortable reserve and carry the operator’s assistance number.": "Sjekk samlet distanse, terreng, vær og batterirekkevidde. Ha god reserve og ta med utleierens telefonnummer for hjelp.",
  "Decide how to get home before setting off. If you plan to enjoy beers, finish the cycling first and spend the evening on foot.": "Bestem hvordan dere skal komme hjem før avreise. Hvis dere vil nyte øl, gjør dere ferdig med syklingen først og ta kvelden til fots.",
  "Renting two e-bikes": "Leie av to elsykler",
  "Reserve two correctly sized bikes, locks and chargers. Confirm pickup and return times, cross-border travel, ferry carriage and breakdown support. Range depends on hills, assistance level and conditions: ask the rental operator about your actual route.": "Reserver to sykler i riktig størrelse, låser og ladere. Bekreft hente- og returtider, grensepassering, transport på ferge og hjelp ved havari. Rekkevidden avhenger av bakker, assistansenivå og forhold. Spør utleieren om akkurat deres rute.",
  "Konstanz rental ↗": "Sykkelleie i Konstanz ↗",
  "Bregenz rental ↗": "Sykkelleie i Bregenz ↗",
  "Swiss rental finder ↗": "Finn sykkelleie i Sveits ↗",
  "Use the lake as a shortcut": "Bruk innsjøen som snarvei",
  "The Konstanz–Meersburg and Friedrichshafen–Romanshorn ferries carry bikes. Check the operator’s current sailing times, fares and final return. The Konstanz–Friedrichshafen catamaran has limited bike space; do not depend on boarding with both bikes for a tight connection.": "Fergene Konstanz–Meersburg og Friedrichshafen–Romanshorn tar med sykler. Sjekk aktuelle avganger, priser og siste retur. Katamaranen Konstanz–Friedrichshafen har begrenset sykkelplass. Ikke baser en knapp forbindelse på at begge syklene får plass.",
  "Meersburg ferry ↗": "Fergen til Meersburg ↗",
  "Romanshorn ferry ↗": "Fergen til Romanshorn ↗",
  "Catamaran ↗": "Katamaran ↗",
  "At the hotel": "På hotellet",
  "Confirm secure space for both bikes and permission to charge with your supplied chargers. Covered parking does not necessarily mean locked storage. The hotel details distinguish confirmed facilities from questions still to ask.": "Bekreft sikker plass til begge syklene og tillatelse til å lade med laderne dere har med. Overdekket parkering betyr ikke nødvendigvis låst oppbevaring. Hotellopplysningene skiller mellom dokumenterte fasiliteter og spørsmål dere fortsatt må stille.",
  "On the way": "Underveis",
  "Follow signed cycling routes, slow down around walkers and dismount where required. Carry water, rain protection, a charged phone and an offline copy of your chosen route. Our illustrated map is for choosing an area, not navigation.": "Følg skiltede sykkelruter, senk farten rundt gående og trill sykkelen der det kreves. Ta med vann, regntøy, ladet telefon og en frakoblet kopi av ruten. Illustrasjonskartet vårt hjelper deg å velge område, men er ikke til navigasjon.",
  "Explore the Bodensee cycle-route stages ↗": "Utforsk etappene på Bodensee-sykkelruten ↗",
  "Choose one of the six places →": "Velg ett av de seks stedene →",
  "GET TO KNOW THE LAKE": "BLI KJENT MED INNSJØEN",
  "Bodensee: one lake, several worlds.": "Bodensee: én innsjø, flere verdener.",
  "At first glance it looks like a small inland sea: a broad horizon, ferries crossing between distant towns, and mountains rising beyond the water. But Bodensee, or Lake Constance, is a freshwater lake. Understanding its shape makes the places in this guide much easier to connect.": "Ved første øyekast minner den om et lite innlandshav: vid horisont, ferger mellom fjerne byer og fjell som reiser seg bak vannet. Men Bodensee, også kalt Lake Constance, er en ferskvannssjø. Når du forstår formen, blir det mye enklere å se sammenhengen mellom stedene i guiden.",
  "First, get your bearings": "Først: få oversikt",
  "Germany lies along most of the northern shore, Switzerland along the southern shore, and Austria at the eastern end around Bregenz. Konstanz is the useful exception to a simple north-versus-south picture: the German city sits beside Swiss Kreuzlingen at the western end of the main lake. A walk or ride there can cross a national border without leaving the built-up area.": "Tyskland ligger langs det meste av nordbredden, Sveits langs sørbredden og Østerrike i øst rundt Bregenz. Konstanz er det nyttige unntaket fra et enkelt nord–sør-bilde: Den tyske byen ligger ved siden av sveitsiske Kreuzlingen i vestenden av hovedinnsjøen. Her kan en gå- eller sykkeltur krysse en landegrense uten å forlate bebyggelsen.",
  "The lake system has two principal basins. The large": "Innsjøsystemet har to hovedbassenger. Den store",
  "is the open water between Konstanz, Friedrichshafen, Lindau, Bregenz and the Swiss shore. Its long northwestern arm is the": "er det åpne vannet mellom Konstanz, Friedrichshafen, Lindau, Bregenz og den sveitsiske bredden. Den lange armen mot nordvest heter",
  ", reaching towards Überlingen and Bodman. The smaller": ", og strekker seg mot Überlingen og Bodman. Den mindre",
  "lies west of Konstanz, with Reichenau, shallow bays and the route towards Stein am Rhein. The short Seerhein through Konstanz connects the two basins.": "ligger vest for Konstanz, med Reichenau, grunne bukter og veien mot Stein am Rhein. Den korte elvestrekningen Seerhein gjennom Konstanz forbinder de to bassengene.",
  "Read about the lake's geography →": "Les om innsjøens geografi →",
  "A landscape shaped by water and ice": "Et landskap formet av vann og is",
  "Glaciers shaped the lake basin during the ice ages. The Rhine enters the eastern end from the Alpine region, passes through the lake system and continues west from the Untersee. This helps explain why the east feels close to the mountains while the western bays feel more enclosed. It is also a reminder that the lake is part of a much larger river landscape.": "Isbreer formet innsjøbassenget under istidene. Rhinen kommer inn i øst fra Alpene, går gjennom innsjøsystemet og fortsetter vestover fra Untersee. Det forklarer hvorfor østenden føles nær fjellene, mens de vestlige buktene er mer skjermet. Innsjøen er også del av et langt større elvelandskap.",
  "Lake formation and Rhine geography →": "Innsjøens dannelse og Rhinens geografi →",
  "For a visitor, the practical difference is between following the shore and turning inland. The waterfront links many towns, but the land behind it rises into hills, vineyards, orchards and hop country. A destination that looks close on a map can involve considerably more climbing than a ride beside the lake. Meersburg's upper town and the hills around Tettnang are good examples; the Pfänder above Bregenz belongs to a different kind of outing altogether.": "For besøkende er det en praktisk forskjell mellom å følge bredden og å dra innover i landet. Vannkanten knytter mange byer sammen, men bak den stiger landskapet med åser, vinmarker, frukthager og humleåkrer. Et sted som ser nært ut på kartet, kan kreve langt mer klatring enn en tur langs innsjøen. Øvre Meersburg og åsene ved Tettnang er gode eksempler. Pfänder over Bregenz er en helt annen type utflukt.",
  "How the six guides fit together": "Slik henger de seks guidene sammen",
  "Konstanz and the west": "Konstanz og vestområdet",
  "suit old-town evenings and island excursions. Use Konstanz as your anchor, then treat Mainau, Reichenau and the farther western towns as individual trips.": "passer for gamlebykvelder og øyutflukter. Bruk Konstanz som base, og ta Mainau, Reichenau og byene lenger vest som egne turer.",
  "Meersburg and Überlingen": "Meersburg og Überlingen",
  "give you castle streets, promenades and the northwestern shore. Unteruhldingen sits between the two and is the stop for the pile-dwelling museum.": "byr på slottsgater, promenader og den nordvestlige bredden. Unteruhldingen ligger mellom dem og er stoppet for museet med pålehus.",
  "Friedrichshafen and hop country": "Friedrichshafen og humleområdet",
  "combine a working lake town, the Zeppelin Museum and the ferry to Romanshorn. Tettnang and the breweries behind the shore add an inland dimension.": "kombinerer en aktiv innsjøby, Zeppelin Museum og fergen til Romanshorn. Tettnang og bryggeriene bak bredden gir turen en dimensjon innover i landet.",
  "is the compact island chapter: harbour, lanes, inns and several evening stops close together.": "er det kompakte øykapitlet: havn, smug, vertshus og flere kveldssteder tett på hverandre.",
  ", farther east, brings the Austrian shore, swimming and the mountain backdrop. The two work well as neighbouring destinations.": ", lenger øst, byr på østerriksk innsjøbredd, bading og fjell i bakgrunnen. De to passer godt som nabomål.",
  "is a chain of towns rather than one centre. Romanshorn is the ferry connection, Arbon makes a useful lakeside stop, and Rorschach adds brewery-bar possibilities. Choose one or two, rather than treating the whole shore as a single neighbourhood.": "er en rekke byer fremfor ett sentrum. Romanshorn har fergeforbindelsen, Arbon er et fint stopp ved vannet, og Rorschach byr på bryggeribarer. Velg én eller to byer, fremfor å behandle hele bredden som ett nabolag.",
  "A little history, visible as you travel": "Litt historie du møter underveis",
  "The lake was a place to live and work long before it became a holiday destination. The pile-dwelling museum at Unteruhldingen introduces the prehistoric settlements of the lakeshore. Later, monasteries became centres of religion, learning and land management. Reichenau's surviving churches preserve evidence of the island's major medieval monastic role; it is now a UNESCO World Heritage Site.": "Innsjøen var et sted å bo og arbeide lenge før den ble et feriemål. Museet i Unteruhldingen viser de forhistoriske bosetningene ved vannet. Senere ble klostrene sentre for religion, læring og jordforvaltning. Kirkene som er bevart på Reichenau, vitner om øyas betydelige klosterrolle i middelalderen. Øya står nå på UNESCOs verdensarvliste.",
  "In 1414–1418, Konstanz hosted a council that brought church and political leaders together during the division of the Western Church. Martin V was elected pope in 1417. It gives the town's old streets a significance beyond their present-day shops and taverns.": "I 1414–1418 var Konstanz vertskap for et kirkemøte som samlet kirkelige og politiske ledere under splittelsen i den vestlige kirken. Martin V ble valgt til pave i 1417. Det gir de gamle gatene en betydning utover dagens butikker og vertshus.",
  "City history of Konstanz →": "Byhistorien til Konstanz →",
  "Friedrichshafen tells a later story through its airship heritage. That contrast is part of the pleasure of travelling here: a medieval island town, a monastery, a brewery and a museum of modern engineering can all belong to the same lake holiday.": "Friedrichshafen forteller en nyere historie gjennom luftskipene. Nettopp kontrastene gjør området spennende: en middelalderby på en øy, et kloster, et bryggeri og et museum for moderne ingeniørkunst kan inngå i samme innsjøferie.",
  "Borrow a bike, return it elsewhere?": "Leie sykkel og levere et annet sted?",
  "There are useful local bike-sharing options, but they do not form one connected network around Bodensee.": "Det finnes nyttige lokale bysykkeltilbud, men de utgjør ikke ett sammenhengende nettverk rundt Bodensee.",
  "Konrad in Konstanz": "Konrad i Konstanz",
  "lets you return regular bikes at another suitable station, including Mainau and Staad.": "lar deg levere vanlige sykler ved en annen passende stasjon, blant annet Mainau og Staad.",
  "Dott in Friedrichshafen": "Dott i Friedrichshafen",
  "offers app-based electric bicycles with permitted local return locations.": "tilbyr elsykler via app med tillatte lokale leveringssteder.",
  "RegiVelo, using Donkey Republic,": "RegiVelo, via Donkey Republic,",
  "serves Kreuzlingen and nearby Swiss communities. Check available bikes and the permitted destination in the app before you unlock.": "dekker Kreuzlingen og nærliggende sveitsiske kommuner. Sjekk ledige sykler og tillatt leveringssted i appen før du låser opp.",
  "For a longer ride between towns, a conventional rental may suit you better. Agree any one-way return with the rental company first. A bike that you can ride over a border is not necessarily a bike you can leave on the other side. Konrad explicitly allows riding into Switzerland, but ending the rental there is not allowed.": "For en lengre tur mellom byer kan vanlig sykkelutleie passe bedre. Avtal eventuell enveisretur med utleieren først. At en sykkel kan brukes over en landegrense, betyr ikke nødvendigvis at den kan leveres på den andre siden. Konrad tillater uttrykkelig sykling inn i Sveits, men leien kan ikke avsluttes der.",
  "Open Bike hire on the map →": "Åpne sykkelleie på kartet →",
  "Konrad cross-border rules": "Konrads regler for grensepassering",
  "Three countries: what happens at the border?": "Tre land: hva skjer ved grensen?",
  "Germany, Austria and Switzerland are all in the Schengen area, so a day ride can cross an international border without the formalities of entering Schengen from outside. Konstanz and Kreuzlingen sit next to each other; a ride east from Lindau takes you into Austria on the way to Bregenz. However, police checks and temporary border controls can occur. Carry your valid passport, or a national identity card accepted for your nationality and journey; a driving licence is not a substitute. Travellers who require visas or residence documents should carry the relevant documents too.": "Tyskland, Østerrike og Sveits er alle med i Schengen. En dagstur kan derfor krysse landegrenser uten de samme formalitetene som ved innreise til Schengen utenfra. Konstanz og Kreuzlingen ligger side om side. Østover fra Lindau sykler du inn i Østerrike på vei til Bregenz. Politikontroller og midlertidig grensekontroll kan likevel forekomme. Ha med gyldig pass, eller et nasjonalt ID-kort som er godkjent for ditt statsborgerskap og din reise. Førerkort erstatter ikke dette. Reisende som trenger visum eller oppholdsdokumenter, bør også ha med disse.",
  "Travel documents for your nationality": "Reisedokumenter for ditt statsborgerskap",
  "Current temporary border controls": "Aktuelle midlertidige grensekontroller",
  "Switzerland still has a customs border.": "Sveits har fortsatt en tollgrense.",
  "Schengen concerns people, not duty-free shopping. If you buy goods to carry across, check the allowances for your direction of travel, particularly for alcohol, tobacco and food. Normal personal travel belongings are treated differently from purchases.": "Schengen gjelder personer, ikke avgiftsfri handel. Hvis du tar med innkjøpte varer over grensen, må du sjekke kvotene for reiseretningen, særlig for alkohol, tobakk og mat. Vanlige personlige reiseeiendeler behandles annerledes enn innkjøp.",
  "Swiss customs guide": "Sveitsisk tollveiledning",
  "Money and mobile data change too.": "Valuta og mobildata endrer seg også.",
  "Germany and Austria use euros; Switzerland uses Swiss francs. Check your mobile plan before using data in Switzerland: EU/EEA roaming rules do not automatically include it. This matters when you need an app to unlock or return a shared bike.": "Tyskland og Østerrike bruker euro, mens Sveits bruker sveitsiske franc. Sjekk mobilabonnementet før du bruker data i Sveits. EU/EØS-reglene for roaming omfatter ikke Sveits automatisk. Det er særlig viktig når du trenger en app for å låse opp eller levere en bysykkel.",
  "Roaming coverage explained": "Forklaring av roamingdekning",
  "For rental bikes:": "For leiesykler:",
  "confirm cross-border permission with the operator and keep its return rules separate from your own right to cross. The same travel-document and customs considerations apply when you cross the lake by international ferry; check bicycle carriage separately.": "Bekreft tillatelse til grensepassering med utleieren, og skill leveringsreglene fra din egen rett til å krysse grensen. De samme hensynene til reisedokumenter og toll gjelder på internasjonale ferger. Sjekk sykkeltransport separat.",
  "Think in shores and crossings": "Tenk i bredder og kryssinger",
  "The water joins places as well as separating them. Konstanz–Meersburg and Friedrichshafen–Romanshorn are useful ferry links, but a straight line across the map is not automatically a convenient connection. Check the terminals, bike carriage and return sailing before building a day around a crossing.": "Vannet binder steder sammen samtidig som det skiller dem. Konstanz–Meersburg og Friedrichshafen–Romanshorn er nyttige fergeforbindelser, men en rett linje på kartet betyr ikke automatisk en praktisk forbindelse. Sjekk terminaler, sykkeltransport og returavganger før dere bygger dagen rundt en kryssing.",
  "For your trip, a simple rhythm works well: choose a base with an evening you like, ride out to one worthwhile stop, and return with time to park the bikes. The local guides supply those stops; the pub guide helps you decide where you would enjoy finishing the day.": "En enkel rytme fungerer godt: Velg en base med et kveldsmiljø dere liker, sykle til ett interessant stopp og kom tilbake i tide til å parkere syklene. De lokale guidene gir turmålene. Pubguiden hjelper dere å velge hvor dagen skal avsluttes.",
  "Explore the pub guide →": "Utforsk pubguiden →",
  "Plan a day by bike →": "Planlegg en sykkeldag →",
  "Choose a place on the map →": "Velg et sted på kartet →",
  "AROUND THE WHOLE LAKE": "RUNDT HELE INNSJØEN",
  "From Irish pubs and neighbourhood bars to brewery tables and lakeside beer gardens. All 26 researched listings are here, grouped by shore.": "Fra irske puber og nabolagsbarer til bryggeribord og ølhager ved vannet. Her finner du alle de 26 undersøkte stedene, gruppert etter område.",
  "Start with the town where you will spend the evening. Finish riding before drinking, then explore on foot. A brewery name alone does not mean there is a public taproom: this directory includes places to visit, with the type of venue clearly marked.": "Start med byen der dere vil tilbringe kvelden. Avslutt syklingen før dere drikker, og utforsk videre til fots. Et bryggerinavn betyr ikke automatisk en åpen bryggeribar. Oversikten viser steder å besøke, med tydelig angitt stedstype.",
  "Find a pub or town": "Finn en pub eller by",
  "Type": "Type",
  "All types": "Alle typer",
  "About the coverage": "Om dekningen",
  "This is a researched directory, not a complete census of every licensed pub. It covers all six guide areas, including Radolfzell in the west and inland hop-country stops. Meersburg itself, smaller shore villages, Kreuzlingen and the western Swiss shore still need broader coverage. Listings are checked against the linked pages, not by a personal visit or a live opening-status service.": "Dette er en undersøkt oversikt, ikke en fullstendig liste over alle puber med skjenkebevilling. Den dekker alle seks guideområdene, inkludert Radolfzell i vest og stopp i humleområdet. Selve Meersburg, mindre landsbyer, Kreuzlingen og den vestlige sveitsiske bredden trenger bredere dekning. Oppføringene er kontrollert mot lenkede nettsider, ikke gjennom personlige besøk eller sanntidskontroll av åpning.",
  "Mike's Irish Pub has a directory source only; Kolbenfresser is supported by a 2024 official tourism guide. Both are flagged for reconfirmation. Ruppaner is a brewery to know, but is not presented here as a confirmed walk-in pub. Tettnanger Krone's closed traditional restaurant is also excluded.": "Mike's Irish Pub er bare dokumentert i en reiseoversikt, mens Kolbenfresser er omtalt i en offisiell turistguide fra 2024. Begge bør bekreftes på nytt. Ruppaner er et bryggeri å kjenne til, men presenteres ikke som en bekreftet åpen pub. Den stengte tradisjonelle restauranten ved Tettnanger Krone er også utelatt.",
  "Konstanz nightlife directory": "Utelivsoversikt for Konstanz",
  "Bregenz bars directory": "Baroversikt for Bregenz",
  "Radolfzell bars directory": "Baroversikt for Radolfzell",
  "Konstanz & the west": "Konstanz og vestområdet",
  "The most flexible western base: proper town evenings, station-side rental and gentle escapes towards Mainau or Reichenau.": "En fleksibel base i vest: hyggelige bykvelder, sykkelleie ved stasjonen og rolige utflukter mot Mainau eller Reichenau.",
  "Eat & drink": "Mat og drikke",
  "See & explore": "Se og opplev",
  "By bike": "På sykkel",
  "Open the separate pub guide for this area →": "Åpne egen pubguide for dette området →",
  "Where to eat & have a beer": "Hvor kan vi spise og ta en øl?",
  "Start around Konstanz’s harbour and old town: Hafenhalle combines food with a beer-garden stop, while Brauhaus Joh. Albrecht is the brewery-table option.": "Start ved havnen og gamlebyen i Konstanz. Hafenhalle kombinerer mat med ølhage, mens Brauhaus Joh. Albrecht er alternativet for en bryggerimiddag.",
  "Take a closer look ↗": "Se nærmere ↗",
  "2 sources": "2 kilder",
  "1 source": "1 kilde",
  "Venue photo not yet verified": "Bilde av stedet er ikke bekreftet ennå",
  "In town & around it": "I byen og nærområdet",
  "Explore by bike": "Utforsk på sykkel",
  "A DAY BY BIKE": "EN DAG PÅ SYKKEL",
  "About 8–12 km each way · editorial estimate": "Omtrent 8–12 km hver vei · redaksjonelt anslag",
  "Start at the station, follow the signed cycling route towards Mainau, then park at the entrance and explore the gardens on foot. Return the same way; keep Reichenau for a separate outing rather than squeezing both islands into one day.": "Start ved stasjonen og følg skiltet sykkelrute mot Mainau. Parker ved inngangen og utforsk hagene til fots. Sykle tilbake samme vei. Ta Reichenau som en egen utflukt, fremfor å presse begge øyene inn på én dag.",
  "Check the route, surface and return options before setting off. This is an outing idea, not turn-by-turn navigation.": "Sjekk rute, underlag og returmuligheter før avreise. Dette er et turforslag, ikke detaljert navigasjon.",
  "Check cycling directions ↗": "Sjekk sykkelruten ↗",
  "Lake cycle-route stages ↗": "Sykkelrutens etapper ↗",
  "Read the general biking guide →": "Les den generelle sykkelguiden →",
  "Rentals & lake crossings": "Sykkelleie og båtkryssinger",
  "3 sources": "3 kilder",
  "Where to stay": "Hvor kan vi bo?",
  "Choose your dates on Booking.com for current prices. Bike storage and charging notes are in each hotel’s details.": "Velg datoer på Booking.com for aktuelle priser. Opplysninger om sykkeloppbevaring og lading står i hotellbeskrivelsene.",
  "Bike charging: check with hotel": "Sykkellading: spør hotellet",
  "View on Booking.com ↗": "Se på Booking.com ↗",
  "← Back to the lake": "← Tilbake til innsjøen",
  "Browse the north-west shore for promenades, stilt houses and a castle stop. Upper Meersburg adds a climb; the waterfront is the easy option.": "Utforsk den nordvestlige bredden med promenader, pålehus og et slottsbesøk. Øvre Meersburg gir noen høydemeter. Vannkanten er det enklere alternativet.",
  "Use Meersburg or Überlingen’s waterfront as your meal stop. In Ueberlingen, the Faulen Pelz offers an inn and beer-garden stop, while Galgenhoelzle is the pub option. Max & Moritz is a farther inland detour.": "Spis ved vannet i Meersburg eller Überlingen. I Überlingen har Faulen Pelz vertshus og ølhage, mens Galgenhoelzle er pubalternativet. Max & Moritz ligger lenger innover i landet.",
  "About 5–8 km each way · editorial estimate": "Omtrent 5–8 km hver vei · redaksjonelt anslag",
  "Start by the harbour and follow the shore towards Unteruhldingen for the Pfahlbauten museum. Return when you feel ready. Visit upper Meersburg on foot afterwards: the castle is above the waterfront. Überlingen is an optional longer outing, not part of this short ride.": "Start ved havnen og følg bredden mot Unteruhldingen og Pfahlbauten-museet. Snu når dere ønsker. Besøk øvre Meersburg til fots etterpå, siden slottet ligger over vannkanten. Überlingen er en mulig lengre utflukt, ikke del av denne korte turen.",
  "Ask your accommodation about the nearest rental operator and reserve two e-bikes ahead of time. Confirm stock and pickup arrangements directly.": "Spør overnattingsstedet om nærmeste utleier og reserver to elsykler på forhånd. Bekreft tilgjengelighet og henting direkte.",
  "Friedrichshafen & hop country": "Friedrichshafen og humleområdet",
  "A useful transport hub with a more rural beer detour behind it. Tettnang and Kressbronn-Berg are inland and hillier than the shore.": "Et nyttig transportknutepunkt med mulighet for ølavstikkere på landet. Tettnang og Kressbronn-Berg ligger inne i landet og er mer kuperte enn bredden.",
  "Die Speiserei at Hotel Maier is the food-focused option. Hopfengut makes sense on an inland outing. Tettnanger Krone’s traditional restaurant is closed, so do not plan dinner there.": "Die Speiserei på Hotel Maier passer når maten står i sentrum. Hopfengut passer på en innlandstur. Tettnanger Krones tradisjonelle restaurant er stengt, så ikke planlegg middag der.",
  "Choose an out-and-back distance that suits you": "Velg en tur-retur-distanse som passer dere",
  "Head east from the harbour, through Eriskirch towards Langenargen, following the signed lakeside cycle route. Stop by the water and return along the same corridor. Treat Tettnang and Hopfengut as a separate, hillier inland day; leave the beer tasting until the riding is finished.": "Dra østover fra havnen gjennom Eriskirch mot Langenargen langs den skiltede sykkelruten. Ta en pause ved vannet og returner samme vei. Ta Tettnang og Hopfengut som en egen, mer kupert innlandsdag. Vent med ølsmaking til syklingen er over.",
  "Bike charging: source linked": "Sykkellading: kilde lenket",
  "Lindau & the island": "Lindau og øya",
  "An island of lanes, old inns and harbour views. A good fit if the best part of the day ends with the bikes parked and dinner on foot.": "En øy med smug, gamle vertshus og havneutsikt. Passer godt når dagens beste del er middag til fots etter at syklene er parkert.",
  "Park the bikes and stay on the island: Engel for inn character, Zur Fischerin for a wine-tavern evening, or Wissingers for the old-brewery setting.": "Parker syklene og bli på øya. Velg Engel for vertshuspreg, Zur Fischerin for en kveld i vinstue eller Wissingers for det gamle bryggerimiljøet.",
  "About 10–15 km each way · editorial estimate": "Omtrent 10–15 km hver vei · redaksjonelt anslag",
  "Leave the island and follow the lakeside cycle corridor through Lochau to Bregenz. Allow time for busy promenades and stops by the water. Return before settling into Lindau’s pubs, or plan a return without cycling if you stay for drinks.": "Forlat øya og følg sykkelveien langs innsjøen gjennom Lochau til Bregenz. Beregn tid til travle promenader og pauser ved vannet. Returner før pubkvelden i Lindau, eller planlegg hjemreise uten sykling hvis dere blir for å ta en drink.",
  "Bregenz & the Austrian shore": "Bregenz og den østerrikske bredden",
  "Combine a compact town base with the lakeside cycle corridor. The Pfänder is a separate mountain outing, best enjoyed without a cycling obligation.": "Kombiner en kompakt bybase med sykkelveien langs innsjøen. Pfänder passer som en egen fjelltur, helst uten forpliktelse til å sykle.",
  "Wirtshaus am See is the checked lakeside inn. Bierbar and Ambiente add town pub options; find them below or in the separate pub guide.": "Wirtshaus am See er det undersøkte vertshuset ved innsjøen. Bierbar og Ambiente gir flere pubalternativer i byen. Du finner dem nedenfor eller i pubguiden.",
  "To Lindau: about 10–15 km each way · editorial estimate": "Til Lindau: omtrent 10–15 km hver vei · redaksjonelt anslag",
  "Ride north along the lake through Lochau towards Lindau, then park and walk the island lanes. Turn back at Lochau for a shorter outing. Keep the Pfänder panorama as a separate mountain visit rather than adding it to a gentle shore ride.": "Sykle nordover langs innsjøen gjennom Lochau mot Lindau. Parker og gå i øyas smågater. Snu ved Lochau for en kortere tur. Ta Pfänder-panoramaet som et eget fjellbesøk, fremfor å legge det til en rolig tur langs bredden.",
  "A string of harbour towns with a quieter feel. Romanshorn connects across the water; Rorschach adds a real brewery bar and a former brewery beer garden.": "En rekke havnebyer med en roligere stemning. Romanshorn har forbindelse over vannet, mens Rorschach byr på en ekte bryggeribar og ølhage i et tidligere bryggeri.",
  "Gustav Kahn is the Romanshorn harbour option; Restaurant Löwengarten combines regional food with a former brewery setting in Rorschach.": "Gustav Kahn er alternativet ved havnen i Romanshorn. Restaurant Löwengarten kombinerer regional mat med et tidligere bryggerimiljø i Rorschach.",
  "Follow the Swiss shore from Arbon towards Rorschach, with time for the harbour. Return the same way for a relaxed outing. If the brewery bars are the main event, park the bikes for the evening and arrange a return that does not involve riding. Romanshorn makes a separate ferry-and-harbour excursion.": "Følg den sveitsiske bredden fra Arbon mot Rorschach og sett av tid til havnen. Returner samme vei for en rolig tur. Hvis bryggeribarene er hovedmålet, parker syklene for kvelden og ordne hjemreise uten sykling. Romanshorn passer som en egen ferge- og havneutflukt.",
  "What to try / do": "Hva kan vi prøve eller gjøre?",
  "Nearby possibilities": "Muligheter i nærheten",
  "Checked sources · 25 September 2026": "Kilder sjekket · 25. september 2026",
  "Brewery & visiting ↗": "Bryggeri og besøk ↗",
  "House beers ↗": "Husets øl ↗",
  "Find on a street map ↗": "Finn på et gatekart ↗",
  "♡ Save this place": "♡ Lagre dette stedet",
  "Restaurant, beer garden & menu ↗": "Restaurant, ølhage og meny ↗",
  "Brewery history & beers ↗": "Bryggerihistorie og øl ↗",
  "Official island arrival guide ↗": "Offisiell veiledning for ankomst til øya ↗",
  "Visitor questions ↗": "Spørsmål fra besøkende ↗",
  "Reichenau visitor information ↗": "Turistinformasjon for Reichenau ↗",
  "Town & visitor information ↗": "By- og turistinformasjon ↗",
  "Outdoor pool & lake access ↗": "Utendørsbasseng og adgang til innsjøen ↗",
  "Thermal baths ↗": "Termalbad ↗",
  "Your evenings": "Kveldene deres",
  "Bike storage": "Sykkeloppbevaring",
  "E-bike charging": "Elsykkellading",
  "Rental access": "Tilgang til sykkelleie",
  "Hotel character & facilities ↗": "Hotellets preg og fasiliteter ↗",
  "Location ↗": "Beliggenhet ↗",
  "Compare rooms": "Sammenlign rom",
  "Choose your dates on Booking.com for current prices and availability.": "Velg datoer på Booking.com for aktuelle priser og ledige rom.",
  "Official Konstanz rental listing ↗": "Offisiell utleieoppføring i Konstanz ↗",
  "Castle visits ↗": "Slottsbesøk ↗",
  "Official museum ↗": "Offisielt museum ↗",
  "Official tourism portal ↗": "Offisiell turistportal ↗",
  "Hotel official information ↗": "Hotellets offisielle informasjon ↗",
  "Regional rentals ↗": "Sykkelleie i regionen ↗",
  "Location & visiting ↗": "Beliggenhet og besøk ↗",
  "English menu ↗": "Meny på engelsk ↗",
  "Official 2026 tour conditions ↗": "Offisielle vilkår for omvisninger i 2026 ↗",
  "Opening hours, tours & beer garden ↗": "Åpningstider, omvisninger og ølhage ↗",
  "Hotel ↗": "Hotell ↗",
  "Restaurant closure notice ↗": "Melding om stengt restaurant ↗",
  "Brewery ↗": "Bryggeri ↗",
  "Bike parking & charging FAQ ↗": "Spørsmål og svar om sykkelparkering og lading ↗",
  "Restaurant information ↗": "Restaurantinformasjon ↗",
  "Hotel & bicycle parking ↗": "Hotell og sykkelparkering ↗",
  "Restaurant & visiting hours ↗": "Restaurant og åpningstider ↗",
  "Current menu page ↗": "Aktuell meny ↗",
  "Inn & kitchen ↗": "Vertshus og kjøkken ↗",
  "Hotel A–Z / hours ↗": "Hotellets A–Å og åpningstider ↗",
  "Tavern & current food ↗": "Vinstue og aktuell mat ↗",
  "Official Lindau visitor information ↗": "Offisiell turistinformasjon for Lindau ↗",
  "Hotel facilities & nearby rental ↗": "Hotellfasiliteter og sykkelleie i nærheten ↗",
  "Hotel bike boxes ↗": "Hotellets sykkelbokser ↗",
  "Tourism listing: charging & rental ↗": "Turistoppføring: lading og utleie ↗",
  "Hotel & bicycle-room information ↗": "Hotell og sykkelrom ↗",
  "Official inn ↗": "Offisielt vertshus ↗",
  "Official panorama guide ↗": "Offisiell panoramaguide ↗",
  "Cable car ↗": "Taubane ↗",
  "Official strandbad ↗": "Offisielt strandbad ↗",
  "City update on completed facilities ↗": "Byens oppdatering om ferdigstilte fasiliteter ↗",
  "Hotel bike storage, charging & location ↗": "Hotellets sykkeloppbevaring, lading og beliggenhet ↗",
  "Local rental operator ↗": "Lokal sykkelutleier ↗",
  "Rental operator ↗": "Sykkelutleier ↗",
  "Beers, bar address & seasonal hours ↗": "Øl, baradresse og sesongåpning ↗",
  "Restaurant, beer garden & tasting conditions ↗": "Restaurant, ølhage og vilkår for smaking ↗",
  "Official venue ↗": "Stedets egen nettside ↗",
  "Official collection & visits ↗": "Offisiell samling og besøk ↗",
  "Hotel bike services & restaurant ↗": "Hotellets sykkelservice og restaurant ↗",
  "Official rental network ↗": "Offisielt utleienettverk ↗",
  "Operator bicycle information ↗": "Operatørens sykkelinformasjon ↗",
  "Ferry information ↗": "Fergeinformasjon ↗",
  "Official ferry timetable & bicycle fares ↗": "Offisielle rutetider og sykkelpriser ↗",
  "Operator bicycle FAQ ↗": "Operatørens spørsmål og svar om sykler ↗",
  "Venue photo not yet verified · see the linked venue source below.": "Bilde av stedet er ikke bekreftet ennå. Se lenken til stedet nedenfor.",
  "Venue / official tourism source ↗": "Stedets nettside eller offisiell turistkilde ↗",
  "Travel-directory listing ↗": "Oppføring i reiseoversikt ↗",
  "App, station map and prices ↗": "App, stasjonskart og priser ↗",
  "Return rules ↗": "Returregler ↗",
  "Cross-border use ↗": "Bruk over landegrenser ↗",
  "City guide to Dott bikes and return rules ↗": "Byens veiledning om Dott-sykler og returregler ↗",
  "Dott app ↗": "Dott-appen ↗",
  "Regional rail guide to RegiVelo ↗": "Regional togoperatørs guide til RegiVelo ↗",
  "How to return a Donkey bike ↗": "Slik leverer du en Donkey-sykkel ↗",
  "Separate cross-border systems ↗": "Separate systemer ved grensen ↗",
  "A proper brewery stop inside the medieval old town. The brewing equipment and historic rooms give the beer a sense of place.": "Et ekte bryggeristopp i middelalderbyen. Bryggeutstyret og de historiske rommene gir ølet en tydelig lokal forankring.",
  "Ask for the current unfiltered house beer and the seasonal kitchen specials.": "Spør etter husets ufiltrerte øl og sesongens retter.",
  "Niederburg lanes, the cathedral and a walk down to the harbour.": "Smugene i Niederburg, domkirken og en spasertur ned til havnen.",
  "The operator currently lists daily opening from noon; check the current kitchen hours before going.": "Operatøren oppgir for tiden daglig åpning fra klokken 12. Sjekk kjøkkenets aktuelle åpningstider før besøket.",
  "The easy “we have arrived” beer garden: boats, lake air and a kitchen with regional roots.": "En lett tilgjengelig ølhage med båter, sjøluft og mat med regionale røtter.",
  "Lentils with Spätzle and Wienerle, or ask about the current fish dishes.": "Linser med Spätzle og Wienerle, eller spør etter dagens fiskeretter.",
  "Harbour, station and old-town evening wander.": "Havnen, stasjonen og en kveldstur i gamlebyen.",
  "Outdoor atmosphere is weather-dependent. Events and menus change.": "Uteserveringen er væravhengig. Arrangementer og menyer kan endres.",
  "A local beer name to recognise around Konstanz, with family brewing history on the lake.": "Et lokalt ølnavn det er verdt å kjenne i Konstanz, med en familiehistorie knyttet til brygging ved innsjøen.",
  "Look for Bio Schimmele or Hefeweizen where stocked.": "Se etter Bio Schimmele eller Hefeweizen der det selges.",
  "Bodensee-Therme and the eastern Konstanz shore.": "Bodensee-Therme og den østlige bredden ved Konstanz.",
  "Brewery reference and detour idea: a walk-in taproom or tour for two has NOT been verified. Do not ride here expecting a public bar.": "Bryggeriet er tatt med som bakgrunn og mulig avstikker. Åpen bryggeribar eller omvisning for to er IKKE bekreftet. Ikke sykle hit med forventning om en offentlig bar.",
  "A colourful break from town streets: gardens, water views and a reason to slow down.": "Et fargerikt avbrekk fra bygater: hager, utsikt over vannet og en grunn til å senke tempoet.",
  "A garden wander with a coffee break; choose the seasonal highlights on the island website.": "En tur i hagene med kaffepause. Se øyas nettside for sesongens høydepunkter.",
  "Konstanz and the northward shore towards Wallhausen.": "Konstanz og bredden nordover mot Wallhausen.",
  "Paid attraction. Check admission and bicycle arrangements before arrival; plan the island visit on foot.": "Inngangsbillett kreves. Sjekk priser og regler for sykler før ankomst, og planlegg å utforske øya til fots.",
  "A slower island detour with monastic heritage and open landscapes. Give it its own generous chunk of time.": "En rolig avstikker til en øy med klosterhistorie og åpent landskap. Sett av godt med tid.",
  "Look for seasonal island produce and explore the heritage sites.": "Se etter sesongens lokale råvarer og utforsk kulturminnene.",
  "Konstanz and the western lake.": "Konstanz og den vestlige delen av innsjøen.",
  "This is a place to browse, not a promise of open churches or a particular farm shop; consult local visitor information.": "Et område å utforske, uten garanti for åpne kirker eller bestemte gårdsbutikker. Se lokal turistinformasjon.",
  "A western extension for old-town wandering when you want more than the main lake shore.": "En avstikker vestover for å vandre i gamlebyen når du vil se mer enn bredden langs hovedinnsjøen.",
  "A slow town walk and a riverside pause.": "En rolig byvandring og en pause ved elven.",
  "Untersee; best treated as a separate outing from Konstanz.": "Untersee. Passer best som en egen utflukt fra Konstanz.",
  "A longer detour, not a short hop. Consult the town visitor information for sights and access.": "En lengre avstikker, ikke en kort tur. Se byens turistinformasjon for severdigheter og adkomst.",
  "A useful choice between a summer swim and a warm-water pause when the weather changes.": "Et godt valg både for sommerbading og et varmt bad når været skifter.",
  "The seasonal outdoor pool and lake access, or the thermal baths.": "Sesongåpent utendørsbasseng og adgang til innsjøen, eller termalbadene.",
  "Ruppaner area and the shore towards Staad.": "Området ved Ruppaner og bredden mot Staad.",
  "Outdoor lake access is seasonal and temperature-dependent. Pool, thermal and sauna admission differ.": "Bading i innsjøen er sesong- og temperaturavhengig. Basseng, termalbad og badstue har ulike billetter.",
  "A traditional town hotel opposite the station: convenient for arrival, rental and an evening without bikes.": "Et tradisjonsrikt byhotell overfor stasjonen, praktisk ved ankomst, sykkelleie og kvelder uten sykkel.",
  "Use it as a town-first base, with Hafenhalle and the old town on foot.": "Bruk hotellet som bybase, med Hafenhalle og gamlebyen innen gangavstand.",
  "Hafenhalle; Joh. Albrecht farther through the old town.": "Hafenhalle. Joh. Albrecht ligger lenger inn i gamlebyen.",
  "The location is verified; hotel bike amenities are not.": "Beliggenheten er bekreftet, men sykkelfasilitetene er ikke bekreftet.",
  "€€–€€€ · comfortable to upscale": "€€–€€€ · komfortabelt til påkostet",
  "Unknown — confirm secure overnight storage.": "Ukjent – bekreft sikker oppbevaring over natten.",
  "Unknown — confirm battery charging policy.": "Ukjent – bekreft reglene for batterilading.",
  "Kultur-Rädle is on Bahnhofplatz; ask about collection and return times.": "Kultur-Rädle ligger på Bahnhofplatz. Spør om hente- og returtider.",
  "A practical e-bike starting point beside the station and old town.": "Et praktisk startpunkt for elsykkelturen ved stasjonen og gamlebyen.",
  "Reserve two correctly sized pedelecs; ask for locks, chargers and route advice.": "Reserver to elsykler i riktig størrelse. Spør om låser, ladere og rutetips.",
  "Hotel Halm and Hafenhalle.": "Hotel Halm og Hafenhalle.",
  "Konstanz tourism confirms pedelecs/e-bikes. Cross-border use, ferry carriage, battery range and return arrangements need agreement with the rental shop.": "Turistkontoret i Konstanz bekrefter utleie av elsykler. Bruk over landegrenser, transport på ferge, rekkevidde og retur må avtales med utleieren.",
  "A castle visit turns a pretty harbour stop into a proper exploration. A good excuse to park up and climb into the town.": "Et slottsbesøk gjør havnestoppen til en ordentlig oppdagelsestur. Parker syklene og gå opp i byen.",
  "Explore the castle and then linger over the lake view.": "Utforsk slottet og nyt utsikten over innsjøen etterpå.",
  "Lower-town waterfront and the Konstanz–Meersburg ferry.": "Sjøfronten i nedre by og fergen Konstanz–Meersburg.",
  "Paid admission; upper town involves gradients and walking. Check current tours directly.": "Inngangsbillett kreves. Øvre by innebærer bakker og gåing. Sjekk aktuelle omvisninger direkte.",
  "Reconstructed lakeside dwellings and original finds make an unusual break between harbour towns.": "Rekonstruerte boliger ved vannet og originale funn gir et annerledes avbrekk mellom havnebyene.",
  "The museum hall, immersive introduction and outdoor dwellings.": "Museumshallen, den sanselige introduksjonen og husene utendørs.",
  "Meersburg and Überlingen along the north-west shore.": "Meersburg og Überlingen langs den nordvestlige bredden.",
  "Paid attraction. Allow time off the bike and check seasonal hours.": "Inngangsbillett kreves. Sett av tid uten sykkel og sjekk sesongens åpningstider.",
  "A generous promenade and historic streets make this a place to linger rather than simply ride through.": "En romslig promenade og historiske gater gjør dette til et sted å bli en stund, ikke bare sykle gjennom.",
  "Walk the old town and gardens, then choose a waterfront café from the local directory.": "Gå gjennom gamlebyen og hagene, og velg deretter en kafé ved vannet fra den lokale oversikten.",
  "St. Nikolaus, town gardens and the western shore.": "St. Nikolaus, byhagene og den vestlige bredden.",
  "A town browsing stop; individual cafés are not endorsed without separate checks.": "Et byområde å utforske. Enkeltkafeer anbefales ikke uten egen kontroll.",
  "A potential base for a more unhurried north-west shore stay, near the promenade and old town.": "En mulig base for et rolig opphold ved den nordvestlige bredden, nær promenaden og gamlebyen.",
  "An evening promenade stroll and food in the old-town restaurant area.": "En kveldstur langs promenaden og middag i gamlebyen.",
  "Überlingen promenade; specific pub matches still to be checked.": "Promenaden i Überlingen. Konkrete puber i nærheten må fortsatt undersøkes.",
  "Candidate hotel, with bike and evening-food research still incomplete.": "Et aktuelt hotell, men kartleggingen av sykkelfasiliteter og kveldsmat er ikke fullført.",
  "€€€ · upscale shortlist": "€€€ · påkostet alternativ",
  "Unknown — confirm locked bike space.": "Ukjent – bekreft låst sykkelplass.",
  "Unknown — confirm e-bike charging.": "Ukjent – bekreft lading av elsykkel.",
  "Use the regional rental directory; a specific nearby e-bike pickup is not yet verified.": "Bruk den regionale utleieoversikten. Et konkret hentested for elsykler i nærheten er ikke bekreftet.",
  "The country brewery detour: head away from the waterfront for house-brewed beer and a substantial meal.": "En avstikker til et bryggeri på landet: dra bort fra vannkanten for husbrygget øl og et solid måltid.",
  "House Helles or Special; choose from the current inn menu.": "Husets Helles eller Special, og mat fra den aktuelle menyen.",
  "Kressbronn and the eastern German shore.": "Kressbronn og den østlige tyske bredden.",
  "Inland hill detour. Private brewery tours list a 10-person minimum; two friends should look for public dates instead.": "En kupert avstikker innover i landet. Private bryggeriturer oppgir minst ti deltakere. To reisende bør se etter offentlige omvisninger.",
  "The most on-theme inland detour: hop growing, museum, brewery, shop and a beer garden in one place.": "En innholdsrik avstikker innover i landet: humledyrking, museum, bryggeri, butikk og ølhage på ett sted.",
  "Ask for the current house beer; fresh-hop specials are seasonal.": "Spør etter husets aktuelle øl. Øl med fersk humle er sesongvare.",
  "Tettnang and its hop-growing countryside.": "Tettnang og landskapet med humledyrking rundt byen.",
  "The operator lists a Monday closure and shorter Sunday restaurant hours. Check public tasting tours; these are more realistic for two than private groups.": "Operatøren oppgir mandagsstengt og kortere restaurantåpning på søndager. Offentlige omvisninger med smaking passer bedre for to enn private gruppeturer.",
  "Eight rooms in a historic brewing house: a characterful alternative if hop country is the focus.": "Åtte rom i et historisk bryggerihus, et særpreget alternativ for deg som vil utforske humleområdet.",
  "Ask where to enjoy the brewery’s Keller-Pils locally.": "Spør hvor bryggeriets Keller-Pils kan nytes lokalt.",
  "Tettnang centre; Hopfengut is a separate inland outing.": "Tettnang sentrum. Hopfengut passer som en egen utflukt.",
  "IMPORTANT: the traditional brewery restaurant is closed. The hotel and brewery remain open. Do not expect dinner downstairs; nearby dinner options need checking.": "VIKTIG: Den tradisjonelle bryggerirestauranten er stengt. Hotellet og bryggeriet er fortsatt åpne. Ikke regn med middag i huset. Andre middagssteder i nærheten må undersøkes.",
  "€€ · small traditional inn": "€€ · lite, tradisjonelt vertshus",
  "Unknown — ask before choosing this base.": "Ukjent – spør før du velger dette som base.",
  "No on-site e-bike rental verified; arrange pickup elsewhere.": "Utleie av elsykler på stedet er ikke bekreftet. Avtal henting et annet sted.",
  "An airship-and-art stop right where the ferry network becomes useful. Keep this one in mind for a rainy spell.": "Luftskip og kunst ved havnen, der ferger gjør det enkelt å komme videre. Et godt alternativ i regnvær.",
  "Browse the current exhibitions before deciding how long to stay.": "Se hvilke utstillinger som vises før du bestemmer hvor lenge du vil bli.",
  "Friedrichshafen promenade and Romanshorn ferry.": "Promenaden i Friedrichshafen og fergen til Romanshorn.",
  "Paid museum; confirm opening days and exhibitions.": "Inngangsbillett kreves. Bekreft åpningsdager og utstillinger.",
  "A food-focused base away from the main-town bustle, with its own restaurant and the lakeshore nearby.": "En base med vekt på mat, utenfor sentrumslivet, med egen restaurant og innsjøen i nærheten.",
  "Dinner at Die Speiserei; inspect the current menu and opening days.": "Middag på Die Speiserei. Sjekk aktuell meny og åpningsdager.",
  "Fischbach shore; central Friedrichshafen is a separate ride or transit journey, not a nearby pub cluster.": "Bredden ved Fischbach. Friedrichshafen sentrum krever en egen sykkel- eller transporttur og er ikke et pubområde rett ved hotellet.",
  "The hotel states the natural beach is 300 m away. Bring the rental charger and confirm access.": "Hotellet oppgir 300 meter til naturstranden. Ta med leiesykkelens lader og avklar tilgangen.",
  "€€–€€€ · comfortable / design rooms": "€€–€€€ · komfortable rom / designrom",
  "Covered bicycle parking verified; whether it is locked is unknown.": "Overdekket sykkelparkering er bekreftet. Det er ukjent om den er låst.",
  "Sockets at pedelec parking verified by hotel FAQ.": "Stikkontakter ved elsykkelparkeringen er bekreftet i hotellets spørsmål og svar.",
  "No on-site rental confirmed. Arrange a regional pickup before arrival.": "Utleie på stedet er ikke bekreftet. Avtal henting i området før ankomst.",
  "A practical town base for promenade evenings and ferry outings.": "En praktisk bybase for kvelder langs promenaden og utflukter med ferge.",
  "An unhurried waterfront evening; check the hotel’s own food and bar offering.": "En rolig kveld ved vannet. Sjekk hotellets eget mat- og bartilbud.",
  "Town-centre restaurants and harbour; named pub shortlist still to be expanded.": "Restauranter i sentrum og havnen. Listen over konkrete puber skal utvides.",
  "A transport-friendly candidate rather than a brewery inn.": "Et aktuelt hotell for enkel transport, fremfor et bryggerivertshus.",
  "€€–€€€ · comfortable town hotel": "€€–€€€ · komfortabelt byhotell",
  "Bicycle spaces in the underground garage verified; individual locking/security arrangements unknown.": "Sykkelplasser i garasjekjelleren er bekreftet. Låsing og sikkerhetsordninger er ukjent.",
  "Unknown — car charging does not establish e-bike charging.": "Ukjent – lading av bil dokumenterer ikke lading av elsykkel.",
  "Town rental options need confirmation; no hotel e-bike rental claimed.": "Utleie i byen må bekreftes. Det hevdes ikke at hotellet leier ut elsykler.",
  "An old-brewery setting with a tucked-away beer garden: a very good reason to stay on the island for the evening.": "Et gammelt bryggerimiljø med en skjermet ølhage, en god grunn til å bli på øya om kvelden.",
  "Browse the current German kitchen menu; the published menu includes ox cheeks and hearty classics.": "Se den aktuelle menyen med tyske retter. Den publiserte menyen inkluderer oksekjaker og solide klassikere.",
  "Engel, Zur Fischerin and the island lanes.": "Engel, Zur Fischerin og smugene på øya.",
  "Operator currently lists Monday and Tuesday as rest days and a break between lunch and dinner. Verify before walking over.": "Operatøren oppgir mandag og tirsdag som hviledager, og pause mellom lunsj og middag. Sjekk før du går dit.",
  "Old rooms, inn character and Bavarian beer: the sort of place that makes parking the bikes for the night worthwhile.": "Historiske rom, vertshuspreg og bayersk øl. Et sted som gjør det verdt å parkere syklene for kvelden.",
  "Regional inn cooking and Vesper; ask about the locally sourced lake fish.": "Regional vertshusmat og Vesper. Spør om lokal fisk fra innsjøen.",
  "Wissingers, island harbour and Hotel Engel upstairs.": "Wissingers, øyas havn og Hotel Engel i etasjene over.",
  "Official pages disagree about Sunday opening. Check directly rather than relying on a saved timetable.": "De offisielle sidene oppgir ulike åpningstider på søndager. Sjekk direkte i stedet for å stole på en lagret oversikt.",
  "A characterful wine tavern with jazz in its history and a creative kitchen. A change of pace from the brewery tables.": "En særpreget vinstue med jazzhistorie og et kreativt kjøkken. Et avbrekk fra bryggerirestaurantene.",
  "Share several dishes from the changing menu; this is a food-and-wine option.": "Del flere retter fra menyen som skifter. Dette er et sted for mat og vin.",
  "Island harbour and the Engel / Wissingers cluster.": "Øyas havn og området rundt Engel og Wissingers.",
  "The operator lists Wednesday–Saturday evenings. Check the current menu.": "Operatøren oppgir kveldsåpent onsdag–lørdag. Sjekk aktuell meny.",
  "A compact island pause with a memorable harbour entrance, then lanes small enough to explore on foot.": "En kompakt øy med en flott innseiling og små gater som passer best å utforske til fots.",
  "A harbour walk before dinner rather than another cycling target.": "En havnetur før middag, fremfor enda et mål for sykkelturen.",
  "Engel, Wissingers, Zur Fischerin and Helvetia.": "Engel, Wissingers, Zur Fischerin og Helvetia.",
  "Busy pedestrian areas are easier with the bike parked. Use local signs for access.": "Travle gågater er enklere når sykkelen er parkert. Følg lokal skilting.",
  "The pub-with-rooms choice: historic inn atmosphere and several dinner options close together.": "Vertshuset med rom: historisk atmosfære og flere middagssteder tett på hverandre.",
  "Engel downstairs, Wissingers or Zur Fischerin on foot.": "Engel i første etasje, Wissingers eller Zur Fischerin til fots.",
  "The island evening cluster and harbour.": "Kveldsstedene på øya og havnen.",
  "Strong evening location, but bike facilities must be checked before committing.": "God beliggenhet for kvelden, men sykkelfasilitetene må sjekkes før bestilling.",
  "€€ · character inn": "€€ · særpreget vertshus",
  "Unknown — confirm secure storage for two e-bikes.": "Ukjent – bekreft sikker oppbevaring av to elsykler.",
  "Unknown — ordinary guest charger lending is not confirmation of e-bike charging.": "Ukjent – utlån av vanlige ladere til gjester bekrefter ikke elsykkellading.",
  "Hotel lists Fahrrad Unger about two minutes away on foot; e-bike stock must be confirmed.": "Hotellet oppgir Fahrrad Unger rundt to minutter unna til fots. Ledige elsykler må bekreftes.",
  "The harbour-and-spa splurge, with the island’s dinner lanes within walking reach.": "Et påkostet alternativ med havneutsikt og spa, i gangavstand til øyas middagssteder.",
  "Harbour time, then Engel, Wissingers or Zur Fischerin.": "Nyt havnen, og gå deretter til Engel, Wissingers eller Zur Fischerin.",
  "Lindau harbour and island station.": "Lindau havn og stasjonen på øya.",
  "Confirm space for both bikes and any charge before choosing rooms.": "Bekreft plass til begge syklene og eventuelle avgifter før du velger rom.",
  "€€€€ · splurge / spa": "€€€€ · påkostet / spa",
  "Bicycle boxes in the YachtGarage verified by hotel FAQ, including for e-bikes.": "Sykkelbokser i YachtGarage er bekreftet i hotellets spørsmål og svar, også for elsykler.",
  "E-bike charging listed by official Lindau tourism; confirm access and sockets.": "Elsykkellading er oppført av turistkontoret i Lindau. Bekreft tilgang og stikkontakter.",
  "Official tourism lists bicycle rental; specifically reserving e-bikes needs confirmation.": "Turistkontoret oppgir sykkelutleie. Reservasjon av elsykler må bekreftes særskilt.",
  "A simpler chain-hotel alternative when the room matters less than the exploring.": "Et enklere kjedehotell når opplevelsene betyr mer enn selve rommet.",
  "Use the hotel bar for an easy last drink; reach the island separately for its pub cluster.": "Hotellets bar passer for en siste drink. Dra til øya for pubene der.",
  "Mainland Lindau; this is not an island-lane base.": "Fastlandet ved Lindau. Dette er ikke en base i øyas smågater.",
  "Value positioning is indicative, not a promise of the cheapest rate. Mainland location trades away immediate island pub access.": "Prisnivået er veiledende, ikke en garanti for laveste pris. Beliggenheten på fastlandet gir lengre vei til pubene på øya.",
  "€ · value-oriented shortlist": "€ · prisbevisst alternativ",
  "Separate bicycle room listed by the operator; fee applies.": "Operatøren oppgir eget sykkelrom mot betaling.",
  "Unknown — confirm suitable charging.": "Ukjent – bekreft egnet lademulighet.",
  "No hotel e-bike rental verified; arrange a Lindau pickup.": "Utleie av elsykler på hotellet er ikke bekreftet. Avtal henting i Lindau.",
  "A traditional lakeside inn for the point when the cycling is done and a long meal sounds exactly right.": "Et tradisjonelt vertshus ved innsjøen for tiden når syklingen er ferdig og du vil nyte et langt måltid.",
  "Choose the current Austrian kitchen specials and ask what beer is on tap.": "Velg blant dagens østerrikske retter og spør hvilket øl de har på fat.",
  "Promenade, festival area and central Bregenz.": "Promenaden, festivalområdet og Bregenz sentrum.",
  "Check current kitchen hours and terrace availability.": "Sjekk kjøkkenets åpningstider og om terrassen er tilgjengelig.",
  "See the lake you have been exploring from above. A clear day makes this a very different kind of detour.": "Se innsjøen ovenfra. På en klar dag gir dette en helt annen opplevelse av området.",
  "The viewing terrace by the upper cable-car station.": "Utsiktsterrassen ved taubanens øvre stasjon.",
  "Bregenz town and Hotel Bodensee.": "Bregenz sentrum og Hotel Bodensee.",
  "Plan a cable-car-and-walking visit. This is not presented as an easy e-bike ascent; weather and operating status matter.": "Planlegg en tur med taubane og gåing. Dette er ikke foreslått som en enkel elsykkeloppstigning. Vær og driftsstatus er avgjørende.",
  "A swim break with proper facilities, close to the town and waterfront.": "En badepause med gode fasiliteter, nær byen og strandpromenaden.",
  "The seasonal strandbad; check indoor options if the weather turns.": "Det sesongåpne strandbadet. Sjekk innendørsalternativer hvis været skifter.",
  "Wirtshaus am See and the promenade.": "Wirtshaus am See og promenaden.",
  "Outdoor swimming is seasonal. Check the operator for opening status and admission.": "Utendørsbading er sesongbasert. Se operatørens opplysninger om åpning og billetter.",
  "A compact central base with the strongest directly documented bike setup on this shortlist.": "En kompakt base i sentrum med de tydeligst dokumenterte sykkelfasilitetene blant disse hotellene.",
  "Walk to central restaurants or Wirtshaus am See; add a Pfänder trip on a clear day.": "Gå til restauranter i sentrum eller Wirtshaus am See. Legg til en tur på Pfänder i klarvær.",
  "Harbour, town centre and Pfänderbahn.": "Havnen, sentrum og Pfänderbahn.",
  "Confirm space and the charging arrangement for your two rental bikes.": "Bekreft plass og ladeordning for begge leiesyklene.",
  "€€ · comfortable central base": "€€ · komfortabel base i sentrum",
  "Lockable bicycle / e-bike storage verified in hotel FAQ.": "Låsbart rom for sykler og elsykler er bekreftet i hotellets spørsmål og svar.",
  "Charging inside the bicycle room explicitly verified.": "Lading inne i sykkelrommet er uttrykkelig bekreftet.",
  "Radverleih Bregenz is a local e-bike operator; confirm pickup location and arrange separately.": "Radverleih Bregenz er en lokal elsykkelutleier. Bekreft hentested og avtal leie separat.",
  "A local operator explicitly offering e-bikes for lakeside riding.": "En lokal utleier som uttrykkelig tilbyr elsykler til turer langs innsjøen.",
  "Ask for two touring-style pedelecs with chargers and locks.": "Spør etter to elsykler egnet for tur, med ladere og låser.",
  "Bregenz base; optional ride towards Lindau.": "Bregenz som base, med mulighet for tur mot Lindau.",
  "Confirm cross-border permission, battery range, pickup address and return deadline directly. No live stock checked.": "Bekreft grensepassering, rekkevidde, hentested og returfrist direkte. Ledige sykler er ikke sjekket i sanntid.",
  "A real small-brewery bar rather than just a beer brand. A good Swiss-side anchor for an evening.": "En ekte bar ved et lite bryggeri, ikke bare et ølmerke. Et godt utgangspunkt for en kveld på sveitsisk side.",
  "Helles, Märzen or the dark “Das Schwarze”; an alcohol-free beer is also listed.": "Helles, Märzen eller det mørke ølet Das Schwarze. Alkoholfritt øl står også på listen.",
  "Rorschach town and Löwengarten, with a separate walk between them.": "Rorschach sentrum og Löwengarten, med en egen spasertur mellom dem.",
  "Bar hours vary between summer and September–May; Sundays closed in the published schedule. The brewery is not the harbour Kornhaus building.": "Barens åpningstider varierer mellom sommeren og september–mai. Søndager er stengt i publisert oversikt. Bryggeriet ligger ikke i Kornhaus-bygningen ved havnen.",
  "A former brewery bottling hall with a shaded beer garden and regional food.": "En tidligere tappehall for øl med skyggefull ølhage og regional mat.",
  "Ask for a regional beer and browse the changing kitchen menu.": "Spør etter et regionalt øl og se den skiftende menyen.",
  "Rorschach; pair with Kornhausbräu as a walking evening after parking the bikes.": "Rorschach. Kombiner med Kornhausbräu som en kveld til fots etter at syklene er parkert.",
  "Published beer-tasting packages are for 10–20 people, so do not assume a private tasting for two.": "Publiserte ølsmakingspakker gjelder grupper på 10–20 personer. Ikke regn med privat smaking for to.",
  "A colourful harbour hangout with a relaxed terrace feel. Handy before or after the ferry.": "Et fargerikt møtested ved havnen med avslappet terrassepreg. Praktisk før eller etter fergen.",
  "The current café/food offer; check whether a brunch date fits your visit.": "Se dagens kafé- og mattilbud, og om en brunsjdato passer besøket.",
  "Romanshorn ferry and autobau.": "Fergen i Romanshorn og autobau.",
  "Food-and-drinks stop, not a verified brewery taproom. Check current opening hours.": "Et sted for mat og drikke, ikke en bekreftet bryggeribar. Sjekk aktuelle åpningstider.",
  "A collection of sports and racing cars gives the Swiss shore a different sort of stop.": "En samling sports- og racerbiler gir den sveitsiske bredden et annerledes stopp.",
  "Check the current visitor programme and exhibition access.": "Sjekk besøksprogrammet og adgangen til utstillingene.",
  "Romanshorn harbour and Gustav Kahn.": "Romanshorn havn og Gustav Kahn.",
  "Paid attraction with specific public visiting times; check before making the detour.": "Inngangsbillett kreves, og offentlige besøk har bestemte tider. Sjekk før avstikkeren.",
  "A bike-oriented Swiss base with a restaurant and the lake cycle route close at hand.": "En sykkelvennlig sveitsisk base med restaurant og sykkelruten langs innsjøen i nærheten.",
  "Dinner in-house, with an Arbon wander when you want a quieter evening.": "Middag på hotellet og en tur i Arbon for en roligere kveld.",
  "Arbon; Rorschach breweries are a separate outing, not a short pub walk.": "Arbon. Bryggeriene i Rorschach er en egen utflukt, ikke en kort pubvandring.",
  "Good cycling credentials; the town pub shortlist still needs more research.": "Gode dokumenterte sykkelfasiliteter. Puboversikten for byen trenger mer kartlegging.",
  "€€–€€€ · comfortable Swiss base": "€€–€€€ · komfortabel sveitsisk base",
  "Secure bicycle cellar and small repair workshop verified.": "Sikker sykkelkjeller og lite reparasjonsverksted er bekreftet.",
  "Not established from the checked source — confirm directly.": "Ikke dokumentert i den sjekkede kilden – bekreft direkte.",
  "Hotel mentions partner rental bikes; e-bike model, collection and availability need confirmation.": "Hotellet nevner sykler fra en samarbeidspartner. Modell, henting og tilgjengelighet for elsykler må bekreftes.",
  "A useful way to investigate Swiss-side bicycle and e-bike pickup options.": "En nyttig oversikt for å undersøke henting av sykler og elsykler på sveitsisk side.",
  "Search the operator’s stations for your chosen base and verify the model before reserving.": "Søk etter stasjoner ved basen din og bekreft sykkelmodellen før reservasjon.",
  "Choose a station to match your hotel, not the other way round.": "Velg en stasjon som passer hotellet, ikke omvendt.",
  "This is an operator directory, not a confirmed Romanshorn or Rorschach rental desk. No local stock or one-way return is assumed.": "Dette er en operatøroversikt, ikke et bekreftet utleiested i Romanshorn eller Rorschach. Lokal tilgjengelighet og enveisretur er ikke bekreftet.",
  "A useful bridge between the western town base and the north shore, with bicycle carriage.": "En nyttig forbindelse mellom Konstanz-området og nordbredden, med plass til sykler.",
  "Use it to open another shore without committing to the long way around.": "Bruk fergen for å oppleve en annen bredd uten å sykle hele veien rundt.",
  "Staad is outside central Konstanz; allow time to ride to the correct terminal.": "Staad ligger utenfor Konstanz sentrum. Beregn tid til riktig terminal.",
  "Check current timetable and bicycle fare with Stadtwerke. This is not the central-harbour passenger ship.": "Sjekk aktuelle rutetider og sykkelpris hos Stadtwerke. Dette er ikke passasjerbåten fra sentrumshavnen.",
  "The most useful cross-lake link for a German / Swiss mix, with bicycles and e-bikes listed in the fare table.": "En nyttig forbindelse tvers over innsjøen mellom Tyskland og Sveits. Sykler og elsykler er oppført i prislisten.",
  "A harbour-to-harbour switch of country, then explore locally.": "Bytt land fra havn til havn og utforsk området lokalt.",
  "Zeppelin Museum on one side; Gustav Kahn and autobau on the other.": "Zeppelin Museum på én side, Gustav Kahn og autobau på den andre.",
  "Consult the live timetable and return sailing. Confirm your rental agreement covers Switzerland.": "Se oppdaterte rutetider og siste returavgang. Bekreft at leieavtalen tillater bruk i Sveits.",
  "A passenger link between two useful town bases, but bicycle space is the limiting factor.": "En passasjerforbindelse mellom to gode bybaser, men med begrenset plass til sykler.",
  "Consider a foot-passenger outing if you want a relaxed beer evening across the lake.": "Vurder en tur uten sykkel hvis dere ønsker en rolig ølkveld på den andre siden.",
  "Konstanz and Friedrichshafen centres.": "Sentrum i Konstanz og Friedrichshafen.",
  "Operator FAQ says a maximum of 10 bicycles per crossing. Carriage is not guaranteed; check current arrangements and allow another option.": "Operatørens spørsmål og svar oppgir maksimalt ti sykler per avgang. Plass er ikke garantert. Sjekk gjeldende regler og ha et alternativ.",
  "An Irish-pub option in the centre of Konstanz, with Irish and German draught beers.": "En irsk pub i Konstanz sentrum med irsk og tysk fatøl.",
  "Guinness, Kilkenny or a German draught beer; check the current food and events menus.": "Guinness, Kilkenny eller tysk fatøl. Sjekk aktuelle menyer og arrangementer.",
  "See the Konstanz and western lake area guide for nearby stays, sights and cycling ideas.": "Se områdeguiden for Konstanz og den vestlige innsjøen for overnatting, severdigheter og sykkelturer i nærheten.",
  "Source checked 25 September 2026. Check current hours, food service and events directly; this is not a live opening-status check.": "Kilden ble sjekket 25. september 2026. Sjekk aktuelle åpningstider, matservering og arrangementer direkte. Åpningsstatus er ikke kontrollert i sanntid.",
  "The Seerhein branch gives you an alternative to the old-town pub circuit.": "Avdelingen ved Seerhein gir et alternativ til pubrunden i gamlebyen.",
  "A pint and a sporting event; confirm the programme for your evening.": "En øl og en sportssending. Bekreft programmet for den aktuelle kvelden.",
  "An Irish pub for a straightforward pub evening in Konstanz.": "En irsk pub for en avslappet pubkveld i Konstanz.",
  "Explore the current beer selection, including alcohol-free choices.": "Utforsk ølutvalget, også de alkoholfrie alternativene.",
  "A western-lake detour with a central bar and a small food menu.": "En avstikker ved den vestlige innsjøen med en sentral bar og en liten matmeny.",
  "Fish and chips or an oven-baked bread alongside a beer; check kitchen hours.": "Fish and chips eller ovnsbakt brød til ølet. Sjekk kjøkkenets åpningstider.",
  "A neighbourhood pub and beer garden away from the harbour circuit, listed by Konstanz tourism.": "En nabolagspub med ølhage utenfor havneområdet, oppført av turistkontoret i Konstanz.",
  "A casual beer and Vesper-style food; the tourism listing mentions rock music, darts and table football.": "En uformell øl og Vesper-retter. Turistoversikten nevner rockemusikk, dart og bordfotball.",
  "Official tourism guide from 2024; reconfirm current operation before a special trip.": "Offisiell turistguide fra 2024. Bekreft at stedet fortsatt er i drift før en egen tur hit.",
  "A spacious bar with music and events, listed by the local tourist office.": "En romslig bar med musikk og arrangementer, oppført av det lokale turistkontoret.",
  "Check the event programme before choosing between a quiet drink and a lively night.": "Se programmet før du velger mellom en rolig drink og en livlig kveld.",
  "A pub, beer bar and live-music venue with a broad beer selection.": "Pub, ølbar og konsertsted med et bredt ølutvalg.",
  "A beer and a look at the music calendar. The venue describes smoking and non-smoking areas.": "En øl og en titt på musikkprogrammet. Stedet beskriver egne områder for røykere og ikke-røykere.",
  "See the Meersburg and Ueberlingen area guide for nearby stays, sights and cycling ideas.": "Se områdeguiden for Meersburg og Überlingen for overnatting, severdigheter og sykkelturer i nærheten.",
  "A Bavarian-style inn and beer garden by the lake promenade.": "Et vertshus i bayersk stil med ølhage ved strandpromenaden.",
  "Choose a meal and beer from the current menu; outdoor seating depends on conditions.": "Velg mat og øl fra den aktuelle menyen. Uteserveringen avhenger av forholdene.",
  "A casual saloon-style bar with draught beer and bottled dark beer.": "En uformell bar i saloonstil med fatøl og mørkt flaskeøl.",
  "A freshly poured beer, or ask about the dark bottled beer selection.": "Et nytappet øl, eller spør etter utvalget av mørkt flaskeøl.",
  "See the Friedrichshafen and hop country area guide for nearby stays, sights and cycling ideas.": "Se områdeguiden for Friedrichshafen og humleområdet for overnatting, severdigheter og sykkelturer i nærheten.",
  "A substantial waterfront beer garden for an outdoor stop in Friedrichshafen.": "En stor ølhage ved vannet for en utendørspause i Friedrichshafen.",
  "A lakeside table and a beer; check seasonal operation before travelling.": "Et bord ved innsjøen og en øl. Sjekk sesongåpningen før turen.",
  "A restaurant lounge with beers, cocktails and whisky, rather than a traditional pub.": "En restaurantlounge med øl, cocktails og whisky, snarere enn en tradisjonell pub.",
  "An evening drink with food from the lounge menu if wanted.": "En kveldsdrink, eventuelt med mat fra loungemenyen.",
  "An Irish-pub listing in the same island lane as Wissingers.": "En irsk pub oppført i samme gate på øya som Wissingers.",
  "Check directly before visiting: this entry is supported by a travel-directory listing, not a current operator website.": "Sjekk direkte før besøket. Oppføringen bygger på en reiseoversikt, ikke en aktuell nettside fra operatøren.",
  "See the Lindau area guide for nearby stays, sights and cycling ideas.": "Se områdeguiden for Lindau for overnatting, severdigheter og sykkelturer i nærheten.",
  "Directory listing only; current operation and hours need direct confirmation.": "Kun oppføring i en reiseoversikt. Drift og åpningstider må bekreftes direkte.",
  "A beer-bar option listed by Bregenz tourism, useful for an evening in town.": "En ølbar oppført av turistkontoret i Bregenz, aktuell for en kveld i byen.",
  "Check the current beer list and opening hours directly.": "Sjekk dagens ølkart og åpningstider direkte.",
  "See the Bregenz area guide for nearby stays, sights and cycling ideas.": "Se områdeguiden for Bregenz for overnatting, severdigheter og sykkelturer i nærheten.",
  "A pub and billiards option listed by the local tourist office.": "Et sted for pub og biljard, oppført av det lokale turistkontoret.",
  "A drink and a game; confirm table availability and current hours.": "En drink og et parti biljard. Bekreft ledige bord og åpningstider.",
  "A brewery, restaurant and hotel in Arbon: a natural addition to a beer-focused Swiss-shore visit.": "Bryggeri, restaurant og hotell i Arbon. Et naturlig stopp på en tur med vekt på øl langs den sveitsiske bredden.",
  "Ask about house beers and the current restaurant menu.": "Spør etter husets øl og den aktuelle restaurantmenyen.",
  "See the Swiss shore area guide for nearby stays, sights and cycling ideas.": "Se områdeguiden for den sveitsiske bredden for overnatting, severdigheter og sykkelturer i nærheten.",
  "An American bar and restaurant for a different style of Swiss-shore evening.": "En amerikansk bar og restaurant for en annerledes kveld på sveitsisk side.",
  "Look at the current drinks and food menus before deciding.": "Se aktuelle drikke- og matmenyer før du bestemmer deg.",
  "Unlock a regular bicycle with the Mein konrad app and return it at another suitable konrad station. Useful for local one-way outings, including Mainau and the Staad ferry terminal.": "Lås opp en vanlig sykkel med Mein konrad-appen og lever den ved en annen passende konrad-stasjon. Nyttig for lokale enveisutflukter, blant annet til Mainau og fergeterminalen i Staad.",
  "Check both pickup availability and the destination station in Mein konrad before starting. Regular bikes use k RAD or k PLUS stations.": "Sjekk både ledige sykler og returstasjonen i Mein konrad før turen. Vanlige sykler leveres ved k RAD- eller k PLUS-stasjoner.",
  "Konstanz old town, Mainau and the eastern city shore.": "Gamlebyen i Konstanz, Mainau og byens østlige bredd.",
  "You may ride into Switzerland, but cannot end the rental there. Return to an authorised konrad station. Suburban k HEIMAT cargo bikes must return to their original station. This is a local network, not a lake-wide one-way rental.": "Du kan sykle inn i Sveits, men ikke avslutte leien der. Lever ved en godkjent konrad-stasjon. Lastesykler ved k HEIMAT-stasjoner i forstedene må tilbake til utgangspunktet. Dette er et lokalt nettverk, ikke enveisleie rundt hele innsjøen.",
  "The closest option here to Lime-style hiring: find an electric bicycle in the Dott app, unlock it and finish at a permitted location within the local service area.": "Det nærmeste alternativet her til Lime: finn en elsykkel i Dott-appen, lås den opp og avslutt på et tillatt sted innenfor det lokale området.",
  "Choose a bicycle rather than a scooter in the app. Check the current service boundary, return zones, price and availability before unlocking.": "Velg sykkel, ikke sparkesykkel, i appen. Sjekk områdegrense, retursoner, pris og tilgjengelighet før du låser opp.",
  "Friedrichshafen town, waterfront and local connections.": "Friedrichshafen sentrum, sjøfronten og lokale forbindelser.",
  "This is local urban sharing. Do not assume you can leave a bike in another lake town or take it across a border. Follow the app’s permitted return locations and complete the parking photo and end-rental confirmation.": "Dette er lokal bysykkeldeling. Ikke regn med å kunne levere i en annen by ved innsjøen eller ta sykkelen over en landegrense. Følg appens returregler, ta parkeringsbildet og kontroller at leien er avsluttet.",
  "App-based bicycles and e-bikes around Kreuzlingen and neighbouring communities. A useful option for a short ride on the Swiss side of the western lake.": "Sykler og elsykler via app rundt Kreuzlingen og nabokommunene. Et nyttig alternativ for en kort tur på sveitsisk side av den vestlige innsjøen.",
  "Use Donkey Republic to find a bike and check its allowed drop-off locations before renting. Return locations and available bike types are shown in the app.": "Finn en sykkel i Donkey Republic og sjekk tillatte leveringssteder før leie. Appen viser retursteder og tilgjengelige sykkeltyper.",
  "Kreuzlingen, Bottighofen and the western Swiss shore. Listed with the Konstanz & west area because of its location.": "Kreuzlingen, Bottighofen og den vestlige sveitsiske bredden. Ligger i området Konstanz og vest på grunn av beliggenheten.",
  "Do not assume coverage extends to Romanshorn, Arbon or the entire Swiss shore. RegiVelo and konrad are separate systems: you cannot return one operator’s bike to the other’s station. Check current prices and rental conditions in the app.": "Ikke regn med dekning helt til Romanshorn, Arbon eller resten av den sveitsiske bredden. RegiVelo og konrad er separate systemer: syklene kan ikke leveres på hverandres stasjoner. Se aktuelle priser og vilkår i appen.",
  "Harbour tables & old-town breweries": "Bord ved havnen og bryggerier i gamlebyen",
  "Castles, waterfronts & island gardens": "Slott, sjøfronter og øyhager",
  "Follow the scent of hops inland": "Følg humleduften innover i landet",
  "An island made for lingering": "En øy å nyte i ro og mak",
  "Lake swims, mountain views, Austrian inns": "Bading, fjellutsikt og østerrikske vertshus",
  "Harbour cafés & brewery evenings": "Havnekafeer og bryggerikvelder",
  "Photo from the venue’s official website": "Bilde fra stedets offisielle nettside",
  "Language": "Språk",
  "English": "English",
  "Norsk bokmål": "Norsk bokmål",
  "Lake Days — six guides to Bodensee": "Lake Days – seks guider til Bodensee",
  "Pubs": "Puber",
  "Pub": "Pub",
  "Bar": "Bar",
  "Beer garden": "Ølhage",
  "Brewery restaurant": "Bryggerirestaurant",
  "Brewery bar": "Bryggeribar",
  "Inn": "Vertshus",
  "Stay": "Overnatting",
  "Beer": "Øl",
  "Food": "Mat",
  "Explore": "Opplev",
  "Swim": "Bading",
  "Move": "Transport",
  "Germany": "Tyskland",
  "Switzerland": "Sveits",
  "Austria": "Østerrike",
  "25 September 2026": "25. september 2026",
  "Close map": "Lukk kartet",
  "Zoom in": "Zoom inn",
  "Zoom out": "Zoom ut",
  "Close place details": "Lukk stedsopplysninger",
  "Show on the map": "Vis på kartet",
  "Lake guides": "Guider til innsjøen",
  "Six destination guides": "Seks områdeguider",
  "In this guide": "I denne guiden",
  "Pub guide by shore": "Pubguide etter område",
  "Export saved places ↓": "Eksporter lagrede steder ↓",
  "Your saved places": "Dine lagrede steder",
  "Tap a heart inside a guide to save a place here.": "Trykk på et hjerte i guiden for å lagre et sted her.",
  "Save a few places with the hearts first.": "Lagre noen steder med hjertene først.",
  "Saved-place list exported.": "Listen over lagrede steder er eksportert.",
  "Choose a destination, or use a filter to discover places around the lake.": "Velg et reisemål, eller bruk et filter for å finne steder rundt innsjøen.",
  "Places in this guide, grouped by area. Tap a count to browse; pins mark areas, not venue addresses.": "Stedene i guiden er gruppert etter område. Trykk på et tall for å se listen. Markørene viser områder, ikke nøyaktige adresser.",
  "Bike hire & sharing": "Sykkelleie og bysykler",
  "Photos & details →": "Bilder og detaljer →",
  "Show all areas": "Vis alle områder",
  "Visit": "Besøk",
  "Try a brewery restaurant such as Joh. Albrecht, or make a day of Hopfengut No20: hops, brewing, a museum and a meal. Check each listing for visits and tour arrangements.": "Prøv en bryggerirestaurant som Joh. Albrecht, eller sett av en dag til Hopfengut No20 med humle, brygging, museum og et måltid. Se hvert sted for besøks- og omvisningsordninger.",
  "Pick up here, leave there? Try konrad in Konstanz, Dott in Friedrichshafen or RegiVelo near Kreuzlingen. These are separate local networks. Check the allowed return point before unlocking. Conventional rental options are also listed below.": "Hente her og levere der? Prøv konrad i Konstanz, Dott i Friedrichshafen eller RegiVelo ved Kreuzlingen. Dette er separate lokale nettverk. Sjekk tillatt retursted før du låser opp. Vanlige utleiere er også oppført nedenfor.",
  "Crossing borders with a rental bike →": "Over landegrensen med leiesykkel →",
  "Station-to-station": "Fra stasjon til stasjon",
  "App parking zones": "Parkeringssoner i appen",
  "Designated return locations": "Bestemte retursteder",
  "Conventional rental · confirm return": "Vanlig utleie · avtal retur",
  "Try Bregenz, Irish, brewery...": "Prøv Bregenz, irsk, bryggeri …",
  "No matches. Try another town or clear the filters.": "Ingen treff. Prøv en annen by eller nullstill filtrene.",
  "Ruppaner brewery": "Ruppaner bryggeri",
  "Mainau island": "Øya Mainau",
  "Reichenau island": "Øya Reichenau",
  "Bodensee-Therme & summer lido": "Bodensee-Therme og sommerbad",
  "Pfahlbauten museum": "Pfahlbauten-museet",
  "Überlingen promenade & old town": "Überlingens promenade og gamleby",
  "Tettnanger Krone hotel & brewery": "Tettnanger Krone hotell og bryggeri",
  "Lindau harbour & island lanes": "Lindau havn og øyas smug",
  "Pfänder panorama": "Utsikt fra Pfänder",
  "Rent a Bike · Swiss rental finder": "Rent a Bike · finn sykkelleie i Sveits",
  "Konstanz–Meersburg ferry": "Fergen Konstanz–Meersburg",
  "Friedrichshafen–Romanshorn ferry": "Fergen Friedrichshafen–Romanshorn",
  "Konstanz–Friedrichshafen catamaran": "Katamaranen Konstanz–Friedrichshafen",
  "konrad bike sharing": "konrad bysykler",
  "Dott electric bike sharing": "Dott elsykkeldeling",
  "Konstanz · harbour": "Konstanz · havnen",
  "Mainau · north of Konstanz": "Mainau · nord for Konstanz",
  "Untersee · Germany": "Untersee · Tyskland",
  "Western detour · Switzerland": "Avstikker vestover · Sveits",
  "Konstanz · eastern shore": "Konstanz · østbredden",
  "Meersburg · upper town": "Meersburg · øvre by",
  "Tettnang · town centre": "Tettnang · sentrum",
  "Friedrichshafen · harbour": "Friedrichshafen · havnen",
  "Friedrichshafen · station / promenade": "Friedrichshafen · stasjon / promenade",
  "Lindau island": "Lindau-øya",
  "Lindau · mainland": "Lindau · fastlandet",
  "Bregenz · lakeside": "Bregenz · ved innsjøen",
  "Bregenz · mountain above town": "Bregenz · fjellet over byen",
  "Romanshorn · harbour": "Romanshorn · havnen",
  "Switzerland · station finder": "Sveits · stasjonsoversikt",
  "Central harbours": "Havnene i sentrum",
  "Ueberlingen - promenade": "Überlingen – promenaden",
  "Friedrichshafen - waterfront promenade": "Friedrichshafen – strandpromenaden",
  "Friedrichshafen · local service area": "Friedrichshafen · lokalt dekningsområde",
  "Kreuzlingen & nearby Swiss towns": "Kreuzlingen og nærliggende sveitsiske byer",
  "Open this area's full guide →": "Åpne hele områdeguiden →",
  "LAKE DAYS — SAVED PLACES": "LAKE DAYS – LAGREDE STEDER",
  "LAKE DAYS - SAVED PLACES": "LAKE DAYS – LAGREDE STEDER",
  "Saved from this browser; no bookings or itinerary.": "Lagret i denne nettleseren. Dette er ikke bestillinger eller en reiseplan.",
  "Konstanz rental": "Sykkelleie i Konstanz",
  "Bregenz rental": "Sykkelleie i Bregenz",
  "Swiss rental finder": "Finn sykkelleie i Sveits",
  "Meersburg ferry": "Fergen til Meersburg",
  "Romanshorn ferry": "Fergen til Romanshorn",
  "Catamaran": "Katamaran",
  "Explore the Bodensee cycle-route stages": "Utforsk etappene på Bodensee-sykkelruten",
  "Take a closer look": "Se nærmere",
  "Check cycling directions": "Sjekk sykkelruten",
  "Lake cycle-route stages": "Sykkelrutens etapper",
  "View on Booking.com": "Se på Booking.com",
  "Brewery & visiting": "Bryggeri og besøk",
  "House beers": "Husets øl",
  "Find on a street map": "Finn på et gatekart",
  "Restaurant, beer garden & menu": "Restaurant, ølhage og meny",
  "Brewery history & beers": "Bryggerihistorie og øl",
  "Official island arrival guide": "Offisiell veiledning for ankomst til øya",
  "Visitor questions": "Spørsmål fra besøkende",
  "Reichenau visitor information": "Turistinformasjon for Reichenau",
  "Town & visitor information": "By- og turistinformasjon",
  "Outdoor pool & lake access": "Utendørsbasseng og adgang til innsjøen",
  "Thermal baths": "Termalbad",
  "Hotel character & facilities": "Hotellets preg og fasiliteter",
  "Location": "Beliggenhet",
  "Official Konstanz rental listing": "Offisiell utleieoppføring i Konstanz",
  "Castle visits": "Slottsbesøk",
  "Official museum": "Offisielt museum",
  "Official tourism portal": "Offisiell turistportal",
  "Hotel official information": "Hotellets offisielle informasjon",
  "Regional rentals": "Sykkelleie i regionen",
  "Location & visiting": "Beliggenhet og besøk",
  "English menu": "Meny på engelsk",
  "Official 2026 tour conditions": "Offisielle vilkår for omvisninger i 2026",
  "Opening hours, tours & beer garden": "Åpningstider, omvisninger og ølhage",
  "Hotel": "Hotell",
  "Restaurant closure notice": "Melding om stengt restaurant",
  "Brewery": "Bryggeri",
  "Bike parking & charging FAQ": "Spørsmål og svar om sykkelparkering og lading",
  "Restaurant information": "Restaurantinformasjon",
  "Hotel & bicycle parking": "Hotell og sykkelparkering",
  "Restaurant & visiting hours": "Restaurant og åpningstider",
  "Current menu page": "Aktuell meny",
  "Inn & kitchen": "Vertshus og kjøkken",
  "Hotel A–Z / hours": "Hotellets A–Å og åpningstider",
  "Tavern & current food": "Vinstue og aktuell mat",
  "Official Lindau visitor information": "Offisiell turistinformasjon for Lindau",
  "Hotel facilities & nearby rental": "Hotellfasiliteter og sykkelleie i nærheten",
  "Hotel bike boxes": "Hotellets sykkelbokser",
  "Tourism listing: charging & rental": "Turistoppføring: lading og utleie",
  "Hotel & bicycle-room information": "Hotell og sykkelrom",
  "Official inn": "Offisielt vertshus",
  "Official panorama guide": "Offisiell panoramaguide",
  "Cable car": "Taubane",
  "Official strandbad": "Offisielt strandbad",
  "City update on completed facilities": "Byens oppdatering om ferdigstilte fasiliteter",
  "Hotel bike storage, charging & location": "Hotellets sykkeloppbevaring, lading og beliggenhet",
  "Local rental operator": "Lokal sykkelutleier",
  "Rental operator": "Sykkelutleier",
  "Beers, bar address & seasonal hours": "Øl, baradresse og sesongåpning",
  "Restaurant, beer garden & tasting conditions": "Restaurant, ølhage og vilkår for smaking",
  "Official venue": "Stedets egen nettside",
  "Official collection & visits": "Offisiell samling og besøk",
  "Hotel bike services & restaurant": "Hotellets sykkelservice og restaurant",
  "Official rental network": "Offisielt utleienettverk",
  "Operator bicycle information": "Operatørens sykkelinformasjon",
  "Ferry information": "Fergeinformasjon",
  "Official ferry timetable & bicycle fares": "Offisielle rutetider og sykkelpriser",
  "Operator bicycle FAQ": "Operatørens spørsmål og svar om sykler",
  "Venue / official tourism source": "Stedets nettside eller offisiell turistkilde",
  "Travel-directory listing": "Oppføring i reiseoversikt",
  "App, station map and prices": "App, stasjonskart og priser",
  "Return rules": "Returregler",
  "Cross-border use": "Bruk over landegrenser",
  "City guide to Dott bikes and return rules": "Byens veiledning om Dott-sykler og returregler",
  "Dott app": "Dott-appen",
  "Regional rail guide to RegiVelo": "Regional togoperatørs guide til RegiVelo",
  "How to return a Donkey bike": "Slik leverer du en Donkey-sykkel",
  "Separate cross-border systems": "Separate systemer ved grensen"
};

Object.assign(window.NB_TEXT,{"OUR BODENSEE TRIP · JUST THE TWO OF US":"VÅR BODENSEE-TUR · BARE OSS TO","Two bikes. One lake.":"To sykler. Én innsjø.","Good beer.":"Godt øl.","Our little guide to lakeside rides, brewery stops and long evenings. Pick a shore and let the day unfold.":"Vår lille guide til sykkelturer langs vannet, bryggeristopp og lange kvelder. Velg en bredd og ta dagen som den kommer."});
